### PR TITLE
more country support WOOO (triple digits!)

### PR DESCRIPTION
**Pull request by razod**
I tested all of these countries with the api!

### CODE REVIEW

**Comment by sqwyer** [comment]
Very epic, triple-digit country support. :eyes:

**Comment by sqwyer** [comment]
@danieljcode can I ask why this wasn't merged? o.o

**Comment by danieljcode** [comment]
> @danieljcode can I ask why this wasn't merged? o.o

You can get a html selector element with all the countries in the world here https://www.freeformatter.com/iso-country-list-html-select.html so adding more countries is a low effort/spam pull request. Sorry...

**Comment by razod** [comment]
> > @danieljcode can I ask why this wasn't merged? o.o
> 
> 
> 
> You can get a html selector element with all the countries in the world here https://www.freeformatter.com/iso-country-list-html-select.html so adding more countries is a low effort/spam pull request. Sorry...

i realize that, however i didnt use that, else i would've used the whole thing, i was looking at a country name list for ideas of what countries to use and then added them, some are in alphabetical order because i used a list that was.

**Pull request closed without merging**
