### PR TITLE
Visual Changes, Deprecated Custom Classes in Favor of Bootstrap Classes, Removed Unused Code

### PR DESCRIPTION
**Pull request by ptrandev**
# Changes

A number of changes, some visual, others code-quality.

- consistent padding through the website
- predicted cases now uses bootstrap card styling
- charts have a white background to increase viewability and improve consistency
- inline css removed
- unused css removed
- bootstrap classes used in favor of custom classes
- fixed "Two Week Predictions" title; it is now centered on mobile
- added News and Social Media title to related section
- predicted cases cards now consistently sized and fully responsive
- fixed some formatting in JS file

# Preview

localhost_8000_ (2)

Screen Shot 2020-10-17 at 12 25 42 PM

### CODE REVIEW

**Comment by ptrandev** [comment]
Merge conflict. I'll resolve this shortly.

**Comment by ptrandev** [comment]
Fixed merge conflicts. Some of my changes didn't go through due to this, but I will add them back in my next pull request.

**Comment by ptrandev** [comment]
I will still need to make sure everything is in working order until this is ready to merge.

**Comment by danieljcode** [comment]
> I will still need to make sure everything is in working order until this is ready to merge.

Let me know when you want me to merge this then 😀

**Review by danieljcode — APPROVED** [review]
Looks great!

**Comment by ptrandev** [comment]
All good to go!

**Comment by danieljcode** [comment]
> All good to go!

Merging now!

**Pull request merged**
