### PR TITLE
added 10 countries to support! 

### PR DESCRIPTION
**Pull request by razod**
i added 10 countries to the list and changed the hyperlink color and hover for the footer!

### CODE REVIEW

**Comment by sqwyer** [comment]
**+1** like the change!

**Comment by danieljcode** [comment]
Do all these countries work with the API? 😄

**Review by danieljcode — COMMENTED** [review]
Looks great!

**Comment by razod** [comment]
> Do all these countries work with the API? 😄

yes! i tested all of them with the api!

**Pull request merged**
