### PR TITLE
added comments above the links in head,in  the HTML-legacyVersion

### PR DESCRIPTION
**Pull request by oshyam**
- Added comment in the head tag so that it will be better understood by a developer or a new learner to start with this project
- Added me to the list of contribution and in the readme
Please do the needful work.
Thank You.

### CODE REVIEW

**Comment by danieljcode** [comment]
Can you show me a svreenshot or video clip of the changes.

**Comment by oshyam** [comment]
@danieljcode sure.
[Drive Link ](https://drive.google.com/drive/folders/13HTYavnSFidkNK2E4-pb497aW4z4tNO4?usp=sharing)
Please consider it and do the needful work.
Thank You.

**Review by danieljcode — COMMENTED** [review]
Sorry I cannot merge this pull request. this is low effort... (Adding comments to code is easy)

**Comment by oshyam** [comment]
It's okay 😔 but you've mentioned that adding name to your contribution is fine.. Even though i have seen some of the people with no or very less code.. Although you've already made the application so i thought of adding comments to that but that's totally ok.

**Pull request closed without merging**
