### PR TITLE
Deployed to Firebase

### PR DESCRIPTION
**Pull request by Srikark-17**
Hello,

I have deployed the React app to Firebase so it's public and the React app wasn't built correctly. I fixed the issue with the React app. You can view the public link here: https://covid-19tracker-8adaf.web.app. Hope this gets merged!

### CODE REVIEW

**Review by danieljcode — COMMENTED** [review]
Why did you remove chartJS from the legacy version folder? and the licence file?

**Comment by Srikark-17** [comment]
I will fix it

**Comment by Srikark-17** [comment]
I fixed this

**Review by danieljcode — APPROVED** [review]
Merging now 👍🏼

**Pull request merged**
